version: '3'

services:
  workerman:
    # image: php:7.4.10-alpine
    build:
      context: .
    container_name: workerman
    restart: always
    # ports:
    #   - 8080:8080
    working_dir: /home/project
    volumes:
      - .:/home/project
    labels:
      - "traefik.http.routers.workerman.rule=Host(`workerman.local.com`)"
      - "traefik.http.services.workerman.loadbalancer.server.port=80"
    networks:
      - web_service
    command: "top"

networks:
  web_service:
    external: true